### ISSUE TITLE
Usar fichero de configuración para iniciar las tablas de la Base de datos

### ISSUE THREAD

**Issue by SergioSevilla** [SergioSevilla/Mod2_Actividad1#9]
Se podría utilizar el fichero yaml para crear el esquema de base de datos (si éste no existiera) y poblar las tablas si fuera el caso.

una posible estructura podría ser:

```
tables:
  PRODUCTOS:
    columns:
        id:
          type: integer
        nombre:
          type: string(255)
        precio:
          type: float
        cantidad:
          type: integer
        example_records:
          - {1,prodcuto1,5}
          - {2,producto2,6}
  AUDITORIA:
    columns:
        id:
          type: integer
        metodo:
          type: string(255)
        URL:
          type: string(255)
        cabeceras:
          type: string(255)
        fecha:
          type: datetime
```
